version: 2
updates:
  - package-ecosystem: npm
    directory: "/vane/backend"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: scope
    groups:
      backend-dev:
        dependency-type: development
      backend-prod:
        dependency-type: production

  - package-ecosystem: npm
    directory: "/vane/frontend"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: scope
    groups:
      frontend-dev:
        dependency-type: development
      frontend-prod:
        dependency-type: production

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/vane"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: scope
