import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { overrideProperty } from './helpers'

const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'vane-backend-services-'))
const configDir = fs.mkdtempSync(path.join(os.tmpdir(), 'vane-backend-config-'))
process.env.DATA_DIR = dataDir
process.env.DDNS_CONFIG_DIR = configDir

const modulesPromise = (async () => {
  const { prisma } = await import('../src/db')
  const configService = await import('../src/services/configService')
  const dockerService = await import('../src/services/dockerService')
  const healthService = await import('../src/services/healthService')
  const cryptoModule = await import('../src/crypto')
  return { prisma, configService, dockerService, healthService, cryptoModule }
})()

void test('configService.fqdn normalizes hostnames', async () => {
  const { configService } = await modulesPromise
  assert.equal(configService.fqdn('example.com', '@'), 'example.com')
  assert.equal(configService.fqdn('example.com', ' vpn '), 'vpn.example.com')
})

void test('configService.generateConfig groups hosts by token and emits warnings', async () => {
  const { prisma, configService, cryptoModule } = await modulesPromise
  const tokenCiphertext1 = cryptoModule.encrypt('token-1')
  const tokenCiphertext2 = cryptoModule.encrypt('token-2')
  const restore = [
    overrideProperty(prisma.host, 'findMany', () => Promise.resolve([
      { id: 1, zone: 'example.com', hostname: '@', recordType: 'A', proxied: true, ttl: 1, description: null, enabled: true, tokenId: 11, token: { name: 'Personal', ciphertext: tokenCiphertext1 } },
      { id: 2, zone: 'example.com', hostname: 'vpn', recordType: 'AAAA', proxied: false, ttl: 300, description: null, enabled: true, tokenId: 11, token: { name: 'Personal', ciphertext: tokenCiphertext1 } },
      { id: 3, zone: 'example.net', hostname: 'home', recordType: 'A', proxied: true, ttl: 600, description: null, enabled: true, tokenId: 11, token: { name: 'Personal', ciphertext: tokenCiphertext1 } },
      { id: 4, zone: 'example.org', hostname: 'edge', recordType: 'BOTH', proxied: true, ttl: 1, description: null, enabled: true, tokenId: 12, token: { name: 'Work', ciphertext: tokenCiphertext2 } },
    ] as any)),
  ]

  try {
    const generated = await configService.generateConfig()
    assert.equal(generated.instances.length, 2)
    assert.equal(generated.instances[0].env.CLOUDFLARE_API_TOKEN, 'token-1')
    assert.equal(generated.instances[0].env.IP4_DOMAINS, 'example.com,home.example.net')
    assert.equal(generated.instances[0].env.IP6_DOMAINS, 'vpn.example.com')
    assert.equal(generated.instances[0].env.PROXIED, 'is(example.com) || is(home.example.net)')
    assert.equal(generated.instances[1].env.DOMAINS, 'edge.example.org')
    assert.match(generated.content, /Generated by Vane/)
    assert.ok(generated.warnings.some((w) => w.includes('Multiple custom TTLs')))
  } finally {
    for (const restoreOne of restore.reverse()) restoreOne()
  }
})

void test('configService.importExistingIfNeeded imports hosts from ddns.env', async () => {
  const { prisma, configService } = await modulesPromise
  const envFile = path.join(configDir, 'ddns.env')
  fs.writeFileSync(envFile, 'CLOUDFLARE_API_TOKEN=plain\nDOMAINS=example.com\n', 'utf8')
  const restore = [
    overrideProperty(prisma.host, 'count', () => Promise.resolve(0)),
    overrideProperty(prisma.apiToken, 'create', ({ data }: any) => Promise.resolve({ id: 3, ...data })),
    overrideProperty(prisma.host, 'create', ({ data }: any) => Promise.resolve({ id: 9, ...data })),
  ]

  try {
    const result = await configService.importExistingIfNeeded()
    assert.equal(result.imported, true)
    assert.match(result.detail, /Imported 1 host/)
  } finally {
    for (const restoreOne of restore.reverse()) restoreOne()
  }
})
