import fs from 'node:fs'
import { prisma } from '../db'
import { config, paths } from '../config'
import { decrypt, encrypt } from '../crypto'
import * as dockerService from './dockerService'
import type { Host, ApiToken } from '@prisma/client'

export function fqdn(zone: string, hostname: string): string {
  const h = hostname.trim()
  if (h === '' || h === '@') return zone
  return `${h}.${zone}`
}

type HostWithToken = Host & { token: ApiToken }

export interface InstanceConfig {
  tokenId: number
  tokenName: string
  env: Record<string, string>
  warnings: string[]
}

export interface GeneratedConfig {
  instances: InstanceConfig[]
  content: string
  warnings: string[]
}

function buildEnvForHosts(hosts: HostWithToken[]): { env: Record<string, string>; warnings: string[] } {
  const warnings: string[] = []
  const apiToken = decrypt(hosts[0].token.ciphertext)

  const ip4: string[] = []
  const ip6: string[] = []
  const both: string[] = []
  const proxiedDomains: string[] = []
  const customTtls = new Set<number>()

  for (const h of hosts) {
    const name = fqdn(h.zone, h.hostname)
    if (h.recordType === 'A') ip4.push(name)
    else if (h.recordType === 'AAAA') ip6.push(name)
    else both.push(name)
    if (h.proxied) proxiedDomains.push(name)
    if (h.ttl && h.ttl !== 1) customTtls.add(h.ttl)
  }

  const env: Record<string, string> = {
    CLOUDFLARE_API_TOKEN: apiToken,
  }
  if (both.length) env.DOMAINS = both.join(',')
  if (ip4.length) env.IP4_DOMAINS = ip4.join(',')
  if (ip6.length) env.IP6_DOMAINS = ip6.join(',')

  const needsIPv4 = both.length > 0 || ip4.length > 0
  const needsIPv6 = both.length > 0 || ip6.length > 0
  if (!needsIPv4) env.IP4_PROVIDER = 'none'
  if (!needsIPv6) env.IP6_PROVIDER = 'none'

  const allNames = [...both, ...ip4, ...ip6]
  if (proxiedDomains.length === 0) env.PROXIED = 'false'
  else if (proxiedDomains.length === allNames.length) env.PROXIED = 'true'
  else env.PROXIED = proxiedDomains.map((d) => `is(${d})`).join(' || ')

  if (customTtls.size === 1) {
    env.TTL = String([...customTtls][0])
  } else if (customTtls.size > 1) {
    warnings.push('Multiple custom TTLs configured for one token; favonia uses one TTL per container. Using "1" (auto).')
  }

  return { env, warnings }
}

export async function generateConfig(): Promise<GeneratedConfig> {
  const hosts = (await prisma.host.findMany({
    where: { enabled: true },
    include: { token: true },
  })) as HostWithToken[]

  if (hosts.length === 0) {
    return { instances: [], content: '# No enabled hosts configured.\n', warnings: ['No enabled hosts configured.'] }
  }

  const byToken = new Map<number, HostWithToken[]>()
  for (const h of hosts) {
    const group = byToken.get(h.tokenId) ?? []
    group.push(h)
    byToken.set(h.tokenId, group)
  }

  const instances: InstanceConfig[] = []
  for (const group of byToken.values()) {
    const { env, warnings } = buildEnvForHosts(group)
    instances.push({ tokenId: group[0].tokenId, tokenName: group[0].token.name, env, warnings })
  }
  instances.sort((a, b) => a.tokenId - b.tokenId)

  const warnings = instances.flatMap((i) => i.warnings)
  return { instances, content: renderCombined(instances, true), warnings }
}

function renderCombined(instances: InstanceConfig[], redact: boolean): string {
  const header = [
    '# Generated by Vane - do not edit by hand.',
    `# Generated at ${new Date().toISOString()}`,
    `# ${instances.length} favonia instance(s), one per Cloudflare API token.`,
    '',
  ].join('\n')

  const sections = instances.map((inst) => {
    const env = redact ? { ...inst.env, CLOUDFLARE_API_TOKEN: '<encrypted>' } : inst.env
    const body = Object.entries(env)
      .map(([k, v]) => `${k}=${v}`)
      .join('\n')
    return `# ── ${dockerService.containerNameForToken(inst.tokenId)} (token: ${inst.tokenName}) ──\n${body}\n`
  })

  return `${header}${sections.join('\n')}`
}


export async function applyAndRestart(note?: string): Promise<{
  warnings: string[]
  recreated: boolean
  message: string
  instances: dockerService.InstanceResult[]
}> {
  const generated = await generateConfig()

  fs.mkdirSync(config.ddnsConfigDir, { recursive: true })
  fs.writeFileSync(paths.ddnsEnvFile(), renderCombined(generated.instances, false) || generated.content, {
    mode: 0o600,
  })

  await prisma.configHistory.create({
    data: { content: renderCombined(generated.instances, true) || generated.content, note: note ?? null },
  })

  if (generated.instances.length === 0) {
    const stopResult = await dockerService.stopAllManaged()
    return { warnings: generated.warnings, recreated: false, message: stopResult.message, instances: [] }
  }

  const { results, removed } = await dockerService.applyInstances(
    generated.instances.map((i) => ({ tokenId: i.tokenId, env: i.env })),
  )
  const recreated = results.every((r) => r.recreated)
  const parts = results.map((r) => r.message)
  if (removed.length) parts.push(`Removed ${removed.length} obsolete instance(s).`)
  return { warnings: generated.warnings, recreated, message: parts.join(' '), instances: results }
}

export async function importExistingIfNeeded(): Promise<{ imported: boolean; detail: string }> {
  const hostCount = await prisma.host.count()
  if (hostCount > 0) return { imported: false, detail: 'Database already populated.' }

  const env = (await dockerService.getContainerEnv()) ?? readEnvFile()
  if (!env?.CLOUDFLARE_API_TOKEN) {
    return { imported: false, detail: 'No existing configuration found to import.' }
  }

  const token = await prisma.apiToken.create({
    data: { name: 'Imported', ciphertext: encrypt(env.CLOUDFLARE_API_TOKEN) },
  })

  const entries: Array<{ names: string; type: 'A' | 'AAAA' | 'BOTH' }> = []
  if (env.DOMAINS) entries.push({ names: env.DOMAINS, type: 'BOTH' })
  if (env.IP4_DOMAINS) entries.push({ names: env.IP4_DOMAINS, type: 'A' })
  if (env.IP6_DOMAINS) entries.push({ names: env.IP6_DOMAINS, type: 'AAAA' })

  const proxiedDefault = env.PROXIED === 'true'
  const ttl = env.TTL && /^\d+$/.test(env.TTL) ? parseInt(env.TTL, 10) : 1

  let created = 0
  for (const entry of entries) {
    for (const raw of entry.names.split(',').map((s) => s.trim()).filter(Boolean)) {
      const { zone, hostname } = splitFqdn(raw)
      try {
        await prisma.host.create({
          data: {
            zone,
            hostname,
            recordType: entry.type,
            proxied: proxiedDefault,
            ttl,
            enabled: true,
            tokenId: token.id,
            description: 'Imported on first launch',
          },
        })
        created++
      } catch {}
    }
  }

  return { imported: true, detail: `Imported ${created} host(s) from existing configuration.` }
}

function readEnvFile(): Record<string, string> | null {
  const file = paths.ddnsEnvFile()
  if (!fs.existsSync(file)) return null
  const env: Record<string, string> = {}
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const idx = trimmed.indexOf('=')
    if (idx > 0) env[trimmed.slice(0, idx)] = trimmed.slice(idx + 1)
  }
  return env
}

function splitFqdn(name: string): { zone: string; hostname: string } {
  const parts = name.split('.')
  if (parts.length <= 2) return { zone: name, hostname: '@' }
  const zone = parts.slice(-2).join('.')
  const hostname = parts.slice(0, -2).join('.')
  return { zone, hostname }
}
